# -*- coding: utf-8 -*-
"""Avance 3 - 27/02/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WjC4Ov5K8-JAWV8p1sBZCYsfVgEdx8Nz

# Cargar los datos
"""

# @title
import pandas as pd # Para manejar los datos en tablas
import os # Para interactuar con el sistema operativo
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import warnings

# Descarga y extracción rápida usando comandos de sistema (Colab/Linux)
if not os.path.exists('pd_speech_features.csv'):
    os.system("wget -q https://archive.ics.uci.edu/static/public/470/parkinson+s+disease+classification.zip")
    os.system("unzip -q parkinson+s+disease+classification.zip && unrar x -y *.rar > /dev/null")

# Leer el CSV directamente (asumiendo que ya se extrajo en la carpeta actual)
df_uci = pd.read_csv('pd_speech_features.csv', header=1).apply(pd.to_numeric)

# @title
# 1. Contar cuántas filas tiene cada ID (deberían ser 3)
print("1. FILAS POR ID")
filas_por_id = df_uci.groupby('id').size()
print(filas_por_id.value_counts())

# 2. Ratio de clases
print("2. RATIO DE CLASES")
print(df_uci['class'].value_counts(normalize=True))

df=df_uci

"""Tenemos un desvalance de los datos

# Experimento 1: Fuga de datos

En este experimento quiero ver si entrenar al modelo con las muestras de manera aletoria o por paciente podría influir en las metricas Accuracy y F1-Score, tambien si esto podría llevar al modelo a generar overfiting, el modelo que se utilizará será random forest (criterion="entropy").

Escogimos el modelo rando forest porque tiene la capacidad de seleccionar las variables más representativas, tambien porque no es necesario reescalar los datos finalmente porque nos puede dar una lista de las variables que el modelo utilizo para clasificar lo que tendría importancia clinica para los medicos.
"""

# @title
X = df.drop(columns=['id', 'class'])# elimina las colunas de id y class
y = df['class'] #Separa las etiquetas en la variable y
groups = df['id'] # Separa las etiquetas de id en la variable grupos

# ============================================================
# MODELO A: SPLIT ALEATORIO (INCORRECTO - DATA LEAKAGE)
# ============================================================

X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
# Aquí se separan los datos de manera aleatoria para el entrenamiento y para el testeo
# Entrenamiento = 80%
# Test = 20%

# Verificar leakage
ids_train_a = set(X_train_a.index.map(df['id'])) #Aquí extrae todos los IDs del conjunto de entrenamiento
ids_test_a = set(X_test_a.index.map(df['id'])) #Aquí extrae todos los IDs del conjunto de test
leakage = ids_train_a.intersection(ids_test_a) #Aquí se extrae todos los IDs que coninciden en los anteriores dos grupos

# Entrenar modelo A
modelo_a = RandomForestClassifier(n_estimators=100, criterion="entropy", random_state=42, n_jobs=-1)
# Se esta entrenando con 100 arboles de decision (Más arboles mayor rendimiento hasta cierto punto) pero hasta que punto?
# n_jobs=-1 esto significa que utilice todos los nucleos del CPU para entrenar más rapido

modelo_a.fit(X_train_a, y_train_a) # Aquí es donde el modelo empieza a aprender
y_pred_a = modelo_a.predict(X_test_a) #Aquí el modelo intenta predecir las clases del test

# Métricas Modelo A
acc_a = accuracy_score(y_test_a, y_pred_a) # predicciones correctas / total
f1_a = f1_score(y_test_a, y_pred_a) #F1 = 2 × (precision × recall) / (precision + recall)
# Precision: De todos los que el modelo dijo "Parkinson", ¿cuántos realmente tenían Parkinson?
# recall: De todos los que realmente tienen Parkinson, ¿cuántos detectó el modelo?

# ============================================================
# MODELO B: SPLIT POR GRUPO (CORRECTO - SIN LEAKAGE)
# ============================================================

# Obtener IDs únicos y hacer split a nivel de ID
unique_ids = df['id'].unique() #Aquí se extrae todos los IDs únicos, no se repiten
ids_train_b, ids_test_b = train_test_split(unique_ids, test_size=0.2, random_state=42, stratify=df.groupby('id')['class'].first())
# unique_ids: Aquí estamos diviendo por paciente no por lineas
# Entrenamiento = 80%
# Test = 20%
# stratify=df.groupby('id')['class'].first() es para agregar a cada paciente su etiqueta

# Crear masks para filtrar
train_mask = df['id'].isin(ids_train_b) #En este codigo se trata de conseguir una lista con etiquetas de true y false del grupo de entrenamiento
test_mask = df['id'].isin(ids_test_b) #En este codigo se trata de conseguir una lista con etiquetas de true y false del grupo de testeo

X_train_b = X[train_mask] # Selecciona a todas las muestras que le pertenece al paciente de un ID en especifico para el grupo de entrenamiento
y_train_b = y[train_mask]
X_test_b = X[test_mask] # Seleccion todas las muestras que le pertenece al paciente de un ID en especifico para el grupo de testeo
y_test_b = y[test_mask]

# Verificar que no hay leakage
ids_train_b_set = set(ids_train_b)
ids_test_b_set = set(ids_test_b)
leakage_b = ids_train_b_set.intersection(ids_test_b_set)

# Entrenar modelo B
modelo_b = RandomForestClassifier(n_estimators=100, criterion="entropy", random_state=42, n_jobs=-1)
# Se esta entrenando con 100 arboles de decision (Más arboles mayor rendimiento hasta cierto punto) pero hasta que punto?
# n_jobs=-1 esto significa que utilice todos los nucleos del CPU para entrenar más rapido

modelo_b.fit(X_train_b, y_train_b) # Aquí es donde el modelo empieza a aprender
y_pred_b = modelo_b.predict(X_test_b)

# Métricas Modelo B
acc_b = accuracy_score(y_test_b, y_pred_b)
f1_b = f1_score(y_test_b, y_pred_b)


#ÁREA DE IMPRESION DE RESULTADOS#
print("-" * 60)
print("MODELO UTILIZADO: Randon forest")
print("-" * 60)

print("-" * 60)
print("MODELO A: Split Aleatorio")
print("-" * 60)

print(f"IDs en train: {len(ids_train_a)}")
print(f"IDs en test: {len(ids_test_a)}")
print(f"IDs compartidos (LEAKAGE): {len(leakage)}")

print("\nMetricas:")
print(f"Accuracy: {acc_a:.4f} ({acc_a*100:.2f}%)")
print(f"F1-Score: {f1_a:.4f} ({f1_a*100:.2f}%)")

#------------------------------------------------------------

print("\n" + "-" * 60)
print("MODELO B: Split por Grupo")
print("-" * 60)

print(f"IDs en train: {len(ids_train_b_set)}")
print(f"IDs en test: {len(ids_test_b_set)}")
print(f"IDs compartilhidos (LEAKAGE): {len(leakage_b)}")

print("\nMetricas:")
print(f"Accuracy: {acc_b:.4f} ({acc_b*100:.2f}%)")
print(f"F1-Score: {f1_b:.4f} ({f1_b*100:.2f}%)")

# @title
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# PREPARACIÓN DE DATOS
# ============================================================
X = df.drop(columns=['id', 'class'])
y = df['class']
groups = df['id']

# Rango de árboles a evaluar
n_arboles = [10, 25, 50, 75, 100, 125, 150, 175, 200, 250, 300]

# ============================================================
# MODELO A: SPLIT ALEATORIO (DATA LEAKAGE)
# ============================================================
X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Listas para almacenar métricas
train_acc_a = []
test_acc_a = []
train_f1_a = []
test_f1_a = []

for n in n_arboles:
    modelo = RandomForestClassifier(n_estimators=n, criterion="entropy", random_state=42, n_jobs=-1)
    modelo.fit(X_train_a, y_train_a)

    # Métricas de entrenamiento
    y_train_pred = modelo.predict(X_train_a)
    train_acc_a.append(accuracy_score(y_train_a, y_train_pred))
    train_f1_a.append(f1_score(y_train_a, y_train_pred))

    # Métricas de test
    y_test_pred = modelo.predict(X_test_a)
    test_acc_a.append(accuracy_score(y_test_a, y_test_pred))
    test_f1_a.append(f1_score(y_test_a, y_test_pred))


# ============================================================
# MODELO B: SPLIT POR GRUPO (SIN LEAKAGE)
# ============================================================
unique_ids = df['id'].unique()
ids_train_b, ids_test_b = train_test_split(
    unique_ids, test_size=0.2, random_state=42,
    stratify=df.groupby('id')['class'].first()
)

train_mask = df['id'].isin(ids_train_b)
test_mask = df['id'].isin(ids_test_b)

X_train_b = X[train_mask]
X_test_b = X[test_mask]
y_train_b = y[train_mask]
y_test_b = y[test_mask]

# Listas para almacenar métricas
train_acc_b = []
test_acc_b = []
train_f1_b = []
test_f1_b = []

for n in n_arboles:
    modelo = RandomForestClassifier(n_estimators=n, criterion="entropy", random_state=42, n_jobs=-1)
    modelo.fit(X_train_b, y_train_b)

    # Métricas de entrenamiento
    y_train_pred = modelo.predict(X_train_b)
    train_acc_b.append(accuracy_score(y_train_b, y_train_pred))
    train_f1_b.append(f1_score(y_train_b, y_train_pred))

    # Métricas de test
    y_test_pred = modelo.predict(X_test_b)
    test_acc_b.append(accuracy_score(y_test_b, y_test_pred))
    test_f1_b.append(f1_score(y_test_b, y_test_pred))


# ============================================================
# GRÁFICAS DE CURVAS DE COMPLEJIDAD
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Curvas de Complejidad: Random Forest\nNúmero de Árboles vs Rendimiento', fontsize=14, fontweight='bold')

# --- Gráfica 1: Accuracy Modelo A ---
ax1 = axes[0, 0]
ax1.plot(n_arboles, train_acc_a, 'b-o', label='Train Accuracy', linewidth=2, markersize=6)
ax1.plot(n_arboles, test_acc_a, 'r-s', label='Test Accuracy', linewidth=2, markersize=6)
ax1.fill_between(n_arboles, train_acc_a, test_acc_a, alpha=0.2, color='purple')
ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('MODELO A: Split Aleatorio (CON LEAKAGE)', fontsize=12, color='red')
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.set_ylim([0.7, 1.02])

# Anotar mejor punto
best_idx_a = np.argmax(test_acc_a)
ax1.annotate(f'Mejor: {test_acc_a[best_idx_a]:.4f}\n(n={n_arboles[best_idx_a]})',
             xy=(n_arboles[best_idx_a], test_acc_a[best_idx_a]),
             xytext=(n_arboles[best_idx_a]+20, test_acc_a[best_idx_a]-0.05),
             arrowprops=dict(arrowstyle='->', color='black'),
             fontsize=10, fontweight='bold')

# --- Gráfica 2: Accuracy Modelo B ---
ax2 = axes[0, 1]
ax2.plot(n_arboles, train_acc_b, 'b-o', label='Train Accuracy', linewidth=2, markersize=6)
ax2.plot(n_arboles, test_acc_b, 'g-s', label='Test Accuracy', linewidth=2, markersize=6)
ax2.fill_between(n_arboles, train_acc_b, test_acc_b, alpha=0.2, color='orange')
ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('Accuracy', fontsize=11)
ax2.set_title('MODELO B: Split por Grupo (SIN LEAKAGE)', fontsize=12, color='green')
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)
ax2.set_ylim([0.6, 1.02])

# Anotar mejor punto
best_idx_b = np.argmax(test_acc_b)
ax2.annotate(f'Mejor: {test_acc_b[best_idx_b]:.4f}\n(n={n_arboles[best_idx_b]})',
             xy=(n_arboles[best_idx_b], test_acc_b[best_idx_b]),
             xytext=(n_arboles[best_idx_b]+20, test_acc_b[best_idx_b]-0.05),
             arrowprops=dict(arrowstyle='->', color='black'),
             fontsize=10, fontweight='bold')

# --- Gráfica 3: F1-Score Modelo A ---
ax3 = axes[1, 0]
ax3.plot(n_arboles, train_f1_a, 'b-o', label='Train F1', linewidth=2, markersize=6)
ax3.plot(n_arboles, test_f1_a, 'r-s', label='Test F1', linewidth=2, markersize=6)
ax3.fill_between(n_arboles, train_f1_a, test_f1_a, alpha=0.2, color='purple')
ax3.set_xlabel('Número de Árboles', fontsize=11)
ax3.set_ylabel('F1-Score', fontsize=11)
ax3.set_title('MODELO A: F1-Score (CON LEAKAGE)', fontsize=12, color='red')
ax3.legend(loc='lower right')
ax3.grid(True, alpha=0.3)
ax3.set_ylim([0.7, 1.02])

# ANOTACIÓN EN n=75
idx_75 = n_arboles.index(75)  # Índice donde n=75
f1_train_75 = train_f1_a[idx_75]
f1_test_75 = test_f1_a[idx_75]

# Anotación con los valores en n=75
ax3.annotate(f'n=75\nTrain F1: {f1_train_75:.4f}\nTest F1: {f1_test_75:.4f}',
             xy=(75, f1_test_75),
             xytext=(75+20, f1_test_75-0.08),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# --- Gráfica 4: F1-Score Modelo B ---
ax4 = axes[1, 1]
ax4.plot(n_arboles, train_f1_b, 'b-o', label='Train F1', linewidth=2, markersize=6)
ax4.plot(n_arboles, test_f1_b, 'g-s', label='Test F1', linewidth=2, markersize=6)
ax4.fill_between(n_arboles, train_f1_b, test_f1_b, alpha=0.2, color='orange')
ax4.set_xlabel('Número de Árboles', fontsize=11)
ax4.set_ylabel('F1-Score', fontsize=11)
ax4.set_title('MODELO B: F1-Score (SIN LEAKAGE)', fontsize=12, color='green')
ax4.legend(loc='lower right')
ax4.grid(True, alpha=0.3)
ax4.set_ylim([0.6, 1.02])

# ANOTACIÓN EN n=75
idx_75_b = n_arboles.index(75)  # Índice donde n=75
f1_train_75_b = train_f1_b[idx_75_b]
f1_test_75_b = test_f1_b[idx_75_b]

# Anotación con los valores en n=75
ax4.annotate(f'n=75\nTrain F1: {f1_train_75_b:.4f}\nTest F1: {f1_test_75_b:.4f}',
             xy=(75, f1_test_75_b),
             xytext=(75+20, f1_test_75_b-0.08),
             arrowprops=dict(arrowstyle='->', color='purple'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='plum', alpha=0.8))

plt.tight_layout()
plt.savefig('curvas_complejidad.png', dpi=150, bbox_inches='tight')
plt.show()

# ============================================================
# GRÁFICA COMPARATIVA DE ERROR (TEST)
# ============================================================

# @title
# ============================================================
# GRÁFICA COMPARATIVA DEL GAP TRAIN-TEST (Modelos A y B)
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Comparación del Gap Train-Test: Modelo A vs Modelo B', fontsize=14, fontweight='bold')

# ============================================================
# Calcular Gap Train-Test para ambos modelos
# ============================================================
gap_train_test_a = [train - test for train, test in zip(train_acc_a, test_acc_a)]
gap_train_test_b = [train - test for train, test in zip(train_acc_b, test_acc_b)]

# ============================================================
# Gráfica 1: Gap Train-Test Comparativo (Barras)
# ============================================================
ax1 = axes[0]

x = np.arange(len(n_arboles))
width = 0.35

bars1 = ax1.bar(x - width/2, gap_train_test_a, width, label='Modelo A (Leakage)',
                color='red', alpha=0.7, edgecolor='black')
bars2 = ax1.bar(x + width/2, gap_train_test_b, width, label='Modelo B (Sin Leakage)',
                color='green', alpha=0.7, edgecolor='black')

ax1.axhline(y=0, color='black', linestyle='-', linewidth=1, alpha=0.5)
ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Gap (Train Accuracy - Test Accuracy)', fontsize=11)
ax1.set_title('Gap Train-Test por Número de Árboles', fontsize=12)
ax1.set_xticks(x)
ax1.set_xticklabels(n_arboles)
ax1.legend(loc='upper right')
ax1.grid(True, alpha=0.3, axis='y')

# ANOTACIÓN EN n=75
idx_75 = n_arboles.index(75)
gap_a_75 = gap_train_test_a[idx_75]
gap_b_75 = gap_train_test_b[idx_75]

ax1.annotate(f'A: {gap_a_75:.4f}',
             xy=(idx_75 - width/2, gap_a_75),
             xytext=(idx_75 - width/2, gap_a_75 + 0.02),
             ha='center', fontsize=9, fontweight='bold', color='red')

ax1.annotate(f'B: {gap_b_75:.4f}',
             xy=(idx_75 + width/2, gap_b_75),
             xytext=(idx_75 + width/2, gap_b_75 + 0.02),
             ha='center', fontsize=9, fontweight='bold', color='green')

# ============================================================
# Gráfica 2: Gap Train-Test Comparativo (Líneas)
# ============================================================
ax2 = axes[1]

ax2.plot(n_arboles, gap_train_test_a, 'r-o', label='Modelo A (Leakage)',
         linewidth=2, markersize=8)
ax2.plot(n_arboles, gap_train_test_b, 'g-s', label='Modelo B (Sin Leakage)',
         linewidth=2, markersize=8)

ax2.axhline(y=0, color='black', linestyle='--', linewidth=1.5, alpha=0.7, label='Sin Gap')
ax2.fill_between(n_arboles, gap_train_test_a, gap_train_test_b, alpha=0.2, color='blue')

ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('Gap (Train Accuracy - Test Accuracy)', fontsize=11)
ax2.set_title('Gap Train-Test: Comparación de Tendencias', fontsize=12)
ax2.legend(loc='upper right')
ax2.grid(True, alpha=0.3)

# ANOTACIÓN EN n=75
ax2.annotate(f'A: {gap_a_75:.4f}',
             xy=(75, gap_a_75),
             xytext=(75+20, gap_a_75+0.01),
             arrowprops=dict(arrowstyle='->', color='red'),
             fontsize=10, fontweight='bold', color='red',
             bbox=dict(boxstyle='round', facecolor='lightcoral', alpha=0.7))

ax2.annotate(f'B: {gap_b_75:.4f}',
             xy=(75, gap_b_75),
             xytext=(75+20, gap_b_75-0.02),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=10, fontweight='bold', color='green',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))

plt.tight_layout()
plt.savefig('gap_train_test_comparativo.png', dpi=150, bbox_inches='tight')
plt.show()


# Interpretación
print("INTERPRETACIÓN:")
if gap_a_75 < gap_b_75:
    print(f"   • El Modelo A tiene menor gap ({gap_a_75:.4f}) que el Modelo B ({gap_b_75:.4f})")
    print(f"   • Esto es INVEROSÍMIL - indica que el Modelo A está sobreestimado por leakage")
else:
    print(f"   • El Modelo B tiene menor gap ({gap_b_75:.4f}) que el Modelo A ({gap_a_75:.4f})")
    print(f"   • Esto es ESPERADO - el Modelo B generaliza mejor")

if abs(gap_a_75) < 0.05:
    print(f"   • El Modelo A parece no tener overfitting (gap < 0.05)")
else:
    print(f"   • El Modelo A PUEDE tener overfitting (gap = {gap_a_75:.4f})")

if abs(gap_b_75) < 0.05:
    print(f"   • El Modelo B generaliza bien (gap < 0.05)")
else:
    print(f"   • El Modelo B PUEDE tener overfitting (gap = {gap_b_75:.4f})")

"""Debido a que el gab entre train-test son mayores 0.15 quiere decir que ambos modelos tiene overfiting. Formas para reducir el overfiting en Randon Forest:
- Usar menos features
- Limitar profundidad del arbol
- Aumentar min_sample_leaf

# Experimento 2: Uso del grupo de validación
La idea de esta experimento es el modelo mejorando el accuaracy, pero como en el experimento 1 vimos que ambos modelos caían en overfiting, vamos a optar para utilizarlo y ver si hay variaciones.
"""

# @title
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# PREPARACIÓN DE DATOS
# ============================================================
X = df.drop(columns=['id', 'class'])
y = df['class']
groups = df['id']

# Rango de árboles a evaluar
n_arboles = [10, 25, 50, 75, 100, 125, 150, 175, 200, 250, 300]

# ============================================================
# MODELO A: SPLIT ALEATORIO (DATA LEAKAGE) - 3 CONJUNTOS
# ============================================================
# Primer split: Train+Val vs Test (80% - 20%)
X_trainval_a, X_test_a, y_trainval_a, y_test_a = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Segundo split: Train vs Validation (75% - 25% del 80% = 60% - 20% total)
X_train_a, X_val_a, y_train_a, y_val_a = train_test_split(
    X_trainval_a, y_trainval_a, test_size=0.25, random_state=42, stratify=y_trainval_a
)

print("=" * 60)
print("MODELO A: Split Aleatorio (CON LEAKAGE)")
print("=" * 60)
print(f"Train: {len(X_train_a)} muestras ({len(X_train_a)/len(X)*100:.1f}%)")
print(f"Validation: {len(X_val_a)} muestras ({len(X_val_a)/len(X)*100:.1f}%)")
print(f"Test: {len(X_test_a)} muestras ({len(X_test_a)/len(X)*100:.1f}%)")

# Verificar leakage
ids_train_a = set(X_train_a.index.map(df['id']))
ids_val_a = set(X_val_a.index.map(df['id']))
ids_test_a = set(X_test_a.index.map(df['id']))
leakage_trainval = ids_train_a.intersection(ids_val_a)
leakage_train = ids_train_a.intersection(ids_test_a)
leakage_val = ids_val_a.intersection(ids_test_a)
print(f"\nLeakage Train-Val: {len(leakage_trainval)} IDs compartidos")
print(f"Leakage Train-Test: {len(leakage_train)} IDs compartidos")
print(f"Leakage Val-Test: {len(leakage_val)} IDs compartidos")

# Listas para almacenar métricas
train_acc_a, val_acc_a, test_acc_a = [], [], []
train_f1_a, val_f1_a, test_f1_a = [], [], []

for n in n_arboles:
    modelo = RandomForestClassifier(n_estimators=n,criterion="entropy", random_state=42, n_jobs=-1)
    modelo.fit(X_train_a, y_train_a)

    # Train
    y_train_pred = modelo.predict(X_train_a)
    train_acc_a.append(accuracy_score(y_train_a, y_train_pred))
    train_f1_a.append(f1_score(y_train_a, y_train_pred))

    # Validation
    y_val_pred = modelo.predict(X_val_a)
    val_acc_a.append(accuracy_score(y_val_a, y_val_pred))
    val_f1_a.append(f1_score(y_val_a, y_val_pred))

    # Test
    y_test_pred = modelo.predict(X_test_a)
    test_acc_a.append(accuracy_score(y_test_a, y_test_pred))
    test_f1_a.append(f1_score(y_test_a, y_test_pred))


# ============================================================
# MODELO B: SPLIT POR GRUPO (SIN LEAKAGE) - 3 CONJUNTOS
# ============================================================
unique_ids = df['id'].unique()

# Primer split: Train+Val vs Test (a nivel de ID)
ids_trainval_b, ids_test_b = train_test_split(
    unique_ids, test_size=0.2, random_state=42,
    stratify=df.groupby('id')['class'].first()
)

# Segundo split: Train vs Validation (a nivel de ID)
ids_train_b, ids_val_b = train_test_split(
    ids_trainval_b, test_size=0.25, random_state=42,
    stratify=[df.loc[df['id'] == id, 'class'].iloc[0] for id in ids_trainval_b]
)

# Crear masks
train_mask = df['id'].isin(ids_train_b)
val_mask = df['id'].isin(ids_val_b)
test_mask = df['id'].isin(ids_test_b)

X_train_b = X[train_mask]
y_train_b = y[train_mask]
X_val_b = X[val_mask]
y_val_b = y[val_mask]
X_test_b = X[test_mask]
y_test_b = y[test_mask]

print("\n" + "=" * 60)
print("MODELO B: Split por Grupo (SIN LEAKAGE)")
print("=" * 60)
print(f"Train: {len(X_train_b)} muestras ({len(X_train_b)/len(X)*100:.1f}%)")
print(f"Validation: {len(X_val_b)} muestras ({len(X_val_b)/len(X)*100:.1f}%)")
print(f"Test: {len(X_test_b)} muestras ({len(X_test_b)/len(X)*100:.1f}%)")

# Verificar que no hay leakage
ids_train_b_set = set(ids_train_b)
ids_val_b_set = set(ids_val_b)
ids_test_b_set = set(ids_test_b)
leakage_trainval_b = ids_train_b_set.intersection(ids_val_b_set)
leakage_train_b = ids_train_b_set.intersection(ids_test_b_set)
leakage_val_b = ids_val_b_set.intersection(ids_test_b_set)
print(f"\nLeakage Train-Val: {len(leakage_trainval_b)} IDs compartidos")
print(f"Leakage Train-Test: {len(leakage_train_b)} IDs compartidos")
print(f"Leakage Val-Test: {len(leakage_val_b)} IDs compartidos")

# Listas para almacenar métricas
train_acc_b, val_acc_b, test_acc_b = [], [], []
train_f1_b, val_f1_b, test_f1_b = [], [], []

for n in n_arboles:
    modelo = RandomForestClassifier(n_estimators=n,criterion="entropy", random_state=42, n_jobs=-1)
    modelo.fit(X_train_b, y_train_b)

    # Train
    y_train_pred = modelo.predict(X_train_b)
    train_acc_b.append(accuracy_score(y_train_b, y_train_pred))
    train_f1_b.append(f1_score(y_train_b, y_train_pred))

    # Validation
    y_val_pred = modelo.predict(X_val_b)
    val_acc_b.append(accuracy_score(y_val_b, y_val_pred))
    val_f1_b.append(f1_score(y_val_b, y_val_pred))

    # Test
    y_test_pred = modelo.predict(X_test_b)
    test_acc_b.append(accuracy_score(y_test_b, y_test_pred))
    test_f1_b.append(f1_score(y_test_b, y_test_pred))


# ============================================================
# GRÁFICAS DE CURVAS DE COMPLEJIDAD (3 CONJUNTOS)
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Curvas de Complejidad: Random Forest con Train/Validation/Test', fontsize=14, fontweight='bold')

# --- Gráfica 1: Accuracy Modelo A ---
ax1 = axes[0, 0]
ax1.plot(n_arboles, train_acc_a, 'b-o', label='Train', linewidth=2, markersize=6)
ax1.plot(n_arboles, val_acc_a, 'm-s', label='Validation', linewidth=2, markersize=6)
ax1.plot(n_arboles, test_acc_a, 'r-^', label='Test', linewidth=2, markersize=6)
ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('MODELO A: Accuracy (CON LEAKAGE)', fontsize=12, color='red')
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.set_ylim([0.7, 1.02])

# Anotar mejor punto en Test
best_idx_a_test = np.argmax(test_acc_a)
ax1.annotate(f'Mejor Test: {test_acc_a[best_idx_a_test]:.4f}\n(n={n_arboles[best_idx_a_test]})',
             xy=(n_arboles[best_idx_a_test], test_acc_a[best_idx_a_test]),
             xytext=(n_arboles[best_idx_a_test]+15, test_acc_a[best_idx_a_test]-0.08),
             arrowprops=dict(arrowstyle='->', color='black'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

# --- Gráfica 2: Accuracy Modelo B ---
ax2 = axes[0, 1]
ax2.plot(n_arboles, train_acc_b, 'b-o', label='Train', linewidth=2, markersize=6)
ax2.plot(n_arboles, val_acc_b, 'm-s', label='Validation', linewidth=2, markersize=6)
ax2.plot(n_arboles, test_acc_b, 'g-^', label='Test', linewidth=2, markersize=6)
ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('Accuracy', fontsize=11)
ax2.set_title('MODELO B: Accuracy (SIN LEAKAGE)', fontsize=12, color='green')
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)
ax2.set_ylim([0.6, 1.02])

# Anotar mejor punto en Test
best_idx_b_test = np.argmax(test_acc_b)
ax2.annotate(f'Mejor Test: {test_acc_b[best_idx_b_test]:.4f}\n(n={n_arboles[best_idx_b_test]})',
             xy=(n_arboles[best_idx_b_test], test_acc_b[best_idx_b_test]),
             xytext=(n_arboles[best_idx_b_test]+15, test_acc_b[best_idx_b_test]-0.08),
             arrowprops=dict(arrowstyle='->', color='black'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

# --- Gráfica 3: F1-Score Modelo A ---
ax3 = axes[1, 0]
ax3.plot(n_arboles, train_f1_a, 'b-o', label='Train', linewidth=2, markersize=6)
ax3.plot(n_arboles, val_f1_a, 'm-s', label='Validation', linewidth=2, markersize=6)
ax3.plot(n_arboles, test_f1_a, 'r-^', label='Test', linewidth=2, markersize=6)
ax3.set_xlabel('Número de Árboles', fontsize=11)
ax3.set_ylabel('F1-Score', fontsize=11)
ax3.set_title('MODELO A: F1-Score (CON LEAKAGE)', fontsize=12, color='red')
ax3.legend(loc='lower right')
ax3.grid(True, alpha=0.3)
ax3.set_ylim([0.7, 1.02])

# ANOTACIÓN SIMPLE EN n=25
idx_25 = n_arboles.index(25)
f1_train_25 = train_f1_a[idx_25]
f1_val_25 = val_f1_a[idx_25]
f1_test_25 = test_f1_a[idx_25]

ax3.annotate(f'n=25\nTrain: {f1_train_25:.4f}\nVal: {f1_val_25:.4f}\nTest: {f1_test_25:.4f}',
             xy=(25, f1_test_25),
             xytext=(25+15, f1_test_25-0.05),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.9))

# --- Gráfica 4: F1-Score Modelo B ---
ax4 = axes[1, 1]
ax4.plot(n_arboles, train_f1_b, 'b-o', label='Train', linewidth=2, markersize=6)
ax4.plot(n_arboles, val_f1_b, 'm-s', label='Validation', linewidth=2, markersize=6)
ax4.plot(n_arboles, test_f1_b, 'g-^', label='Test', linewidth=2, markersize=6)
ax4.set_xlabel('Número de Árboles', fontsize=11)
ax4.set_ylabel('F1-Score', fontsize=11)
ax4.set_title('MODELO B: F1-Score (SIN LEAKAGE)', fontsize=12, color='green')
ax4.legend(loc='lower right')
ax4.grid(True, alpha=0.3)
ax4.set_ylim([0.6, 1.02])

# ANOTACIÓN SIMPLE EN n=50
idx_50 = n_arboles.index(50)
f1_train_50 = train_f1_b[idx_50]
f1_val_50 = val_f1_b[idx_50]
f1_test_50 = test_f1_b[idx_50]

ax4.annotate(f'n=50\nTrain: {f1_train_50:.4f}\nVal: {f1_val_50:.4f}\nTest: {f1_test_50:.4f}',
             xy=(50, f1_test_50),
             xytext=(50+15, f1_test_50-0.05),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.9))

plt.tight_layout()
plt.savefig('curvas_complejidad_3sets.png', dpi=150, bbox_inches='tight')
plt.show()

# @title
# ============================================================
# GRÁFICA COMPARATIVA DE GAPS (Train-Validation y Validation-Test)
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Comparativa de Gaps entre Modelos', fontsize=14, fontweight='bold')

# Calcular gaps
# Gap Train-Validation
gap_train_val_a = [train - val for train, val in zip(train_acc_a, val_acc_a)]
gap_train_val_b = [train - val for train, val in zip(train_acc_b, val_acc_b)]

# Gap Validation-Test
gap_val_test_a = [val - test for val, test in zip(val_acc_a, test_acc_a)]
gap_val_test_b = [val - test for val, test in zip(val_acc_b, test_acc_b)]

# --- Gráfica 1: Gap Train-Validation (Modelo A vs Modelo B) ---
ax1 = axes[0]
ax1.plot(n_arboles, gap_train_val_a, 'r-o', label='Modelo A (Leakage)', linewidth=2, markersize=6)
ax1.plot(n_arboles, gap_train_val_b, 'g-s', label='Modelo B (Sin Leakage)', linewidth=2, markersize=6)
ax1.axhline(y=0, color='black', linestyle='--', linewidth=1.5, alpha=0.7)
ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Gap (Train Accuracy - Validation Accuracy)', fontsize=11)
ax1.set_title('Gap Train-Validation', fontsize=12, fontweight='bold')
ax1.legend(loc='upper right')
ax1.grid(True, alpha=0.3)

# ANOTACIONES: Modelo A en n=25, Modelo B en n=50
idx_25 = n_arboles.index(25)
idx_50 = n_arboles.index(50)

# Modelo A en n=25 (arriba)
gap_tv_a_25 = gap_train_val_a[idx_25]
ax1.annotate(f'A: n=25\n{gap_tv_a_25:.4f}',
             xy=(25, gap_tv_a_25),
             xytext=(40, gap_tv_a_25 + 0.04),
             fontsize=9, fontweight='bold', color='red',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

# Modelo B en n=50 (debajo)
gap_tv_b_50 = gap_train_val_b[idx_50]
ax1.annotate(f'B: n=50\n{gap_tv_b_50:.4f}',
             xy=(50, gap_tv_b_50),
             xytext=(65, gap_tv_b_50 - 0.05),
             fontsize=9, fontweight='bold', color='green',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# --- Gráfica 2: Gap Validation-Test (Modelo A vs Modelo B) ---
ax2 = axes[1]
ax2.plot(n_arboles, gap_val_test_a, 'r-o', label='Modelo A (Leakage)', linewidth=2, markersize=6)
ax2.plot(n_arboles, gap_val_test_b, 'g-s', label='Modelo B (Sin Leakage)', linewidth=2, markersize=6)
ax2.axhline(y=0, color='black', linestyle='--', linewidth=1.5, alpha=0.7)
ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('Gap (Validation Accuracy - Test Accuracy)', fontsize=11)
ax2.set_title('Gap Validation-Test', fontsize=12, fontweight='bold')
ax2.legend(loc='upper right')
ax2.grid(True, alpha=0.3)

# ANOTACIONES: Modelo A en n=25, Modelo B en n=50
# Modelo A en n=25 (arriba)
gap_vt_a_25 = gap_val_test_a[idx_25]
ax2.annotate(f'A: n=25\n{gap_vt_a_25:.4f}',
             xy=(25, gap_vt_a_25),
             xytext=(40, gap_vt_a_25 + 0.04),
             fontsize=9, fontweight='bold', color='red',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

# Modelo B en n=50 (debajo)
gap_vt_b_50 = gap_val_test_b[idx_50]
ax2.annotate(f'B: n=50\n{gap_vt_b_50:.4f}',
             xy=(50, gap_vt_b_50),
             xytext=(65, gap_vt_b_50 - 0.05),
             fontsize=9, fontweight='bold', color='green',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

plt.tight_layout()
plt.savefig('gaps_comparativos.png', dpi=150, bbox_inches='tight')
plt.show()

# @title
# ============================================================
# ANÁLISIS DE IMPORTANCIA DE CARACTERÍSTICAS
# ============================================================
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Usar el mejor número de árboles encontrado (ej: 100)
n_arboles_optimo = 100


# --- MODELO A: Con Leakage ---
modelo_a = RandomForestClassifier(n_estimators=n_arboles_optimo, random_state=42, n_jobs=-1)
modelo_a.fit(X_train_a, y_train_a)

# Obtener importancias
importancias_a = modelo_a.feature_importances_
nombres_features = X.columns

# Crear DataFrame de importancias
df_importancia_a = pd.DataFrame({
    'feature': nombres_features,
    'importancia': importancias_a
}).sort_values('importancia', ascending=False)


# --- MODELO B: Sin Leakage ---
modelo_b = RandomForestClassifier(n_estimators=n_arboles_optimo, random_state=42, n_jobs=-1)
modelo_b.fit(X_train_b, y_train_b)

# Obtener importancias
importancias_b = modelo_b.feature_importances_

# Crear DataFrame de importancias
df_importancia_b = pd.DataFrame({
    'feature': nombres_features,
    'importancia': importancias_b
}).sort_values('importancia', ascending=False)


# ============================================================
# GRÁFICA DE IMPORTANCIA DE CARACTERÍSTICAS
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(16, 8))
fig.suptitle('Importancia de Características: Random Forest (Top 20)', fontsize=14, fontweight='bold')

# --- Gráfica 1: Modelo A ---
top20_a = df_importancia_a.head(20)
ax1 = axes[0]
bars1 = ax1.barh(range(len(top20_a)), top20_a['importancia'].values, color='red', alpha=0.7)
ax1.set_yticks(range(len(top20_a)))
ax1.set_yticklabels(top20_a['feature'].values, fontsize=9)
ax1.invert_yaxis()
ax1.set_xlabel('Importancia', fontsize=11)
ax1.set_title('MODELO A: Top 20 Features (CON LEAKAGE)', fontsize=12, color='red')
ax1.grid(True, alpha=0.3, axis='x')

# Añadir valores en las barras
for i, (bar, val) in enumerate(zip(bars1, top20_a['importancia'].values)):
    ax1.text(val + 0.002, bar.get_y() + bar.get_height()/2, f'{val:.4f}',
             va='center', fontsize=8)

# --- Gráfica 2: Modelo B ---
top20_b = df_importancia_b.head(20)
ax2 = axes[1]
bars2 = ax2.barh(range(len(top20_b)), top20_b['importancia'].values, color='green', alpha=0.7)
ax2.set_yticks(range(len(top20_b)))
ax2.set_yticklabels(top20_b['feature'].values, fontsize=9)
ax2.invert_yaxis()
ax2.set_xlabel('Importancia', fontsize=11)
ax2.set_title('MODELO B: Top 20 Features (SIN LEAKAGE)', fontsize=12, color='green')
ax2.grid(True, alpha=0.3, axis='x')

# Añadir valores en las barras
for i, (bar, val) in enumerate(zip(bars2, top20_b['importancia'].values)):
    ax2.text(val + 0.002, bar.get_y() + bar.get_height()/2, f'{val:.4f}',
             va='center', fontsize=8)

plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

# ============================================================
# COMPARACIÓN DE FEATURES EN AMBOS MODELOS
# ============================================================
print("\n" + "=" * 60)
print("COMPARACIÓN: Features en común en Top 10")
print("=" * 60)

top10_a = set(df_importancia_a.head(10)['feature'].values)
top10_b = set(df_importancia_b.head(10)['feature'].values)

features_comunes = top10_a.intersection(top10_b)
print(f"\nFeatures en común: {len(features_comunes)}")
for f in features_comunes:
    print(f"  - {f}")

"""Lo interesante es que el error bajo en ambos modelos, aún así amos se encuentran con overfiting, tambien algo interesante, es que pudimos extraer las top 20 características que utilizó el modelo para poder clasificar, entre ambos modelos tienen los features tqwt_TKEO_mean_dec_12, std_delta_log_energy, std_delta_delta_log_energy, las dos ultimas mencionadas son las dos principales caracteristicas que ambos modelos utilizaron para clasificar.

# Experimento 3: Optimizar los hiperparámetros
Del modelo B con el grupo de validacion evaluaresmos sus hiperparametros el min_samplee y el max_samples, para ver si mejora el gab o el f1-score o el accuracy
"""

# @title
best_n_est_b = 50

# Variar max_depth
max_depth_range = [3, 5, 7, 10, None]

# Listas para métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []

for max_d in max_depth_range:
    modelo = RandomForestClassifier(
        n_estimators=best_n_est_b,
        criterion="entropy",
        max_depth=max_d,
        random_state=42,
        n_jobs=-1
    )
    modelo.fit(X_train_b, y_train_b)

    # Train
    y_train_pred = modelo.predict(X_train_b)
    train_accuracies.append(accuracy_score(y_train_b, y_train_pred))
    train_f1s.append(f1_score(y_train_b, y_train_pred))

    # Validation
    y_val_pred = modelo.predict(X_val_b)
    val_accuracies.append(accuracy_score(y_val_b, y_val_pred))
    val_f1s.append(f1_score(y_val_b, y_val_pred))

    # Test
    y_test_pred = modelo.predict(X_test_b)
    test_accuracies.append(accuracy_score(y_test_b, y_test_pred))
    test_f1s.append(f1_score(y_test_b, y_test_pred))

    profundidad = "None" if max_d is None else max_d
    print(f"max_depth={profundidad}: Val Acc={val_accuracies[-1]:.4f}, Val F1={val_f1s[-1]:.4f}")

# Calcular gaps
gap_train_val = [train - val for train, val in zip(train_accuracies, val_accuracies)]
gap_val_test = [val - test for val, test in zip(val_accuracies, test_accuracies)]

# Mejor max_depth según Validation
best_max_depth_idx = np.argmax(val_accuracies)
best_max_depth = max_depth_range[best_max_depth_idx]
best_max_depth_plot = "None" if best_max_depth is None else best_max_depth

# @title
# Gráficas
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
max_depth_labels = ["3", "5", "7", "10", "None"]
x = range(len(max_depth_range))

fig.suptitle(f'Variación max_depth - Modelo B (n_estimators={best_n_est_b})', fontsize=14, fontweight='bold')

# Accuracy
ax1 = axes[0, 0]
ax1.plot(x, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=8)
ax1.plot(x, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=8)
ax1.plot(x, test_accuracies, 'g-^', label='Test', linewidth=2, markersize=8)
ax1.set_xticks(x)
ax1.set_xticklabels(max_depth_labels)
ax1.set_xlabel('max_depth', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs max_depth', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.annotate(f'Best\n{max_depth_labels[best_max_depth_idx]}\nVal={val_accuracies[best_max_depth_idx]:.4f}',
             xy=(best_max_depth_idx, val_accuracies[best_max_depth_idx]),
             xytext=(best_max_depth_idx+0.5, val_accuracies[best_max_depth_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# F1-Score
ax2 = axes[0, 1]
ax2.plot(x, train_f1s, 'b-o', label='Train', linewidth=2, markersize=8)
ax2.plot(x, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=8)
ax2.plot(x, test_f1s, 'g-^', label='Test', linewidth=2, markersize=8)
ax2.set_xticks(x)
ax2.set_xticklabels(max_depth_labels)
ax2.set_xlabel('max_depth', fontsize=11)
ax2.set_ylabel('F1-Score', fontsize=11)
ax2.set_title('F1-Score vs max_depth', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)

# Gap Train-Validation
ax3 = axes[1, 0]
ax3.plot(x, gap_train_val, 'orange', marker='o', linestyle='-', label='Gap Train-Val', linewidth=2, markersize=8)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax3.set_xticks(x)
ax3.set_xticklabels(max_depth_labels)
ax3.set_xlabel('max_depth', fontsize=11)
ax3.set_ylabel('Gap (Train - Validation)', fontsize=11)
ax3.set_title('Gap Train-Validation', fontsize=12)
ax3.legend(loc='upper right')
ax3.grid(True, alpha=0.3)

# Gap Validation-Test
ax4 = axes[1, 1]
ax4.plot(x, gap_val_test, 'purple', marker='s', linestyle='-', label='Gap Val-Test', linewidth=2, markersize=8)
ax4.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax4.set_xticks(x)
ax4.set_xticklabels(max_depth_labels)
ax4.set_xlabel('max_depth', fontsize=11)
ax4.set_ylabel('Gap (Validation - Test)', fontsize=11)
ax4.set_title('Gap Validation-Test', fontsize=12)
ax4.legend(loc='upper right')
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('modeloB_max_depth.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\nMejor max_depth: {best_max_depth_plot}")

# @title
# Variar min_samples_leaf
min_samples_leaf_range = [1, 3, 5, 10]

# Listas para métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []

for min_leaf in min_samples_leaf_range:
    modelo = RandomForestClassifier(
        n_estimators=best_n_est_b,
        criterion="entropy",
        max_depth=best_max_depth,
        min_samples_leaf=min_leaf,
        random_state=42,
        n_jobs=-1
    )
    modelo.fit(X_train_b, y_train_b)

    # Train
    y_train_pred = modelo.predict(X_train_b)
    train_accuracies.append(accuracy_score(y_train_b, y_train_pred))
    train_f1s.append(f1_score(y_train_b, y_train_pred))

    # Validation
    y_val_pred = modelo.predict(X_val_b)
    val_accuracies.append(accuracy_score(y_val_b, y_val_pred))
    val_f1s.append(f1_score(y_val_b, y_val_pred))

    # Test
    y_test_pred = modelo.predict(X_test_b)
    test_accuracies.append(accuracy_score(y_test_b, y_test_pred))
    test_f1s.append(f1_score(y_test_b, y_test_pred))

    print(f"min_samples_leaf={min_leaf}: Val Acc={val_accuracies[-1]:.4f}, Val F1={val_f1s[-1]:.4f}")

# Calcular gaps
gap_train_val = [train - val for train, val in zip(train_accuracies, val_accuracies)]
gap_val_test = [val - test for val, test in zip(val_accuracies, test_accuracies)]

# Mejor min_samples_leaf según Validation
best_min_leaf_idx = np.argmax(val_accuracies)
best_min_leaf = min_samples_leaf_range[best_min_leaf_idx]

# @title
# Gráficas
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
x = range(len(min_samples_leaf_range))

fig.suptitle(f'Variación min_samples_leaf - Modelo B (n={best_n_est_b}, max_depth={best_max_depth_plot})', fontsize=14, fontweight='bold')

# Accuracy
ax1 = axes[0, 0]
ax1.plot(x, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=8)
ax1.plot(x, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=8)
ax1.plot(x, test_accuracies, 'g-^', label='Test', linewidth=2, markersize=8)
ax1.set_xticks(x)
ax1.set_xticklabels(min_samples_leaf_range)
ax1.set_xlabel('min_samples_leaf', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs min_samples_leaf', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.annotate(f'Best\nmin_leaf={best_min_leaf}\nVal={val_accuracies[best_min_leaf_idx]:.4f}',
             xy=(best_min_leaf_idx, val_accuracies[best_min_leaf_idx]),
             xytext=(best_min_leaf_idx+0.5, val_accuracies[best_min_leaf_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# F1-Score
ax2 = axes[0, 1]
ax2.plot(x, train_f1s, 'b-o', label='Train', linewidth=2, markersize=8)
ax2.plot(x, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=8)
ax2.plot(x, test_f1s, 'g-^', label='Test', linewidth=2, markersize=8)
ax2.set_xticks(x)
ax2.set_xticklabels(min_samples_leaf_range)
ax2.set_xlabel('min_samples_leaf', fontsize=11)
ax2.set_ylabel('F1-Score', fontsize=11)
ax2.set_title('F1-Score vs min_samples_leaf', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)

# Gap Train-Validation
ax3 = axes[1, 0]
ax3.plot(x, gap_train_val, 'orange', marker='o', linestyle='-', label='Gap Train-Val', linewidth=2, markersize=8)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax3.set_xticks(x)
ax3.set_xticklabels(min_samples_leaf_range)
ax3.set_xlabel('min_samples_leaf', fontsize=11)
ax3.set_ylabel('Gap (Train - Validation)', fontsize=11)
ax3.set_title('Gap Train-Validation', fontsize=12)
ax3.legend(loc='upper right')
ax3.grid(True, alpha=0.3)

# Gap Validation-Test
ax4 = axes[1, 1]
ax4.plot(x, gap_val_test, 'purple', marker='s', linestyle='-', label='Gap Val-Test', linewidth=2, markersize=8)
ax4.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax4.set_xticks(x)
ax4.set_xticklabels(min_samples_leaf_range)
ax4.set_xlabel('min_samples_leaf', fontsize=11)
ax4.set_ylabel('Gap (Validation - Test)', fontsize=11)
ax4.set_title('Gap Validation-Test', fontsize=12)
ax4.legend(loc='upper right')
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('modeloB_min_samples_leaf.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\nMejor min_samples_leaf: {best_min_leaf}")

# @title
# Resumen de mejores hiperparámetros
print("\n" + "=" * 70)
print("RESUMEN: MEJORES HIPERPARÁMETROS - MODELO B (SIN LEAKAGE)")
print("=" * 70)
print(f"   n_estimators: {best_n_est_b}")
print(f"   max_depth: {best_max_depth_plot}")
print(f"   min_samples_leaf: {best_min_leaf}")
print(f"\nMétricas en Validation:")
print(f"   Accuracy: {val_accuracies[best_min_leaf_idx]:.4f}")
print(f"   F1-Score: {val_f1s[best_min_leaf_idx]:.4f}")
print(f"\nGaps en mejor configuración:")
print(f"   Gap Train-Validation: {gap_train_val[best_min_leaf_idx]:.4f}")
print(f"   Gap Validation-Test: {gap_val_test[best_min_leaf_idx]:.4f}")

"""Se aumento el accuracy per no disminuyo muy poco a nivel de milesimas, lo mismo paso con el F1-score aumento a nivel de milesimas.

# Experimento 4: Reducción de dimensionalidad y uso del modelo B

En este experimento queremos reducir las dimensionalidades sin perder el nombre de las mismas, debido a que puede ser de ayuda para el medico. Tambien queremos extraer los datos más significativos que puedan ayudarnos a clasificar en parkison y no parkison. Es por ello que diseñamos un sistema de reduccion de dimensionalidad, primero extraemos todas las variables que tengan una variacion menor a 0.01, luego un segundo filtro con la matriz de correlacion para extraer variables que sean redundantes o tengan una correlacion de maro a 0.95, finalmente un tercer filtro para extraer los 30 top variables utilizando el modelo XGBoost, el cual es similar como una arbol de decision pero puede expandirse.
"""

# @title
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# CARGAR DATOS
# ============================================================

print("=" * 70)
print("EXPERIMENTO: REDUCCIÓN DE DIMENSIONALIDAD")
print("=" * 70)
print(f"\nDataset original: {X.shape[0]} muestras, {X.shape[1]} features")

# ============================================================
# CAPA 1: FILTRO DE VARIANZA
# ============================================================
print("\n" + "-" * 70)
print("CAPA 1: FILTRO DE VARIANZA")
print("-" * 70)

# Calcular varianza de cada feature
varianzas = X.var()
threshold_varianza = 0.01  # Eliminar features con varianza < 0.01

# Features a mantener por varianza
features_varianza = varianzas[varianzas > threshold_varianza].index.tolist()
X_capa1 = X[features_varianza]

print(f"Threshold de varianza: > {threshold_varianza}")
print(f"Features eliminados por baja varianza: {X.shape[1] - len(features_varianza)}")
print(f"Features restantes: {len(features_varianza)}")

# ============================================================
# CAPA 2: FILTRO DE CORRELACIÓN
# ============================================================
print("\n" + "-" * 70)
print("CAPA 2: FILTRO DE CORRELACIÓN")
print("-" * 70)

# Calcular matriz de correlación
corr_matrix = X_capa1.corr().abs()

# Seleccionar triángulo superior de la matriz
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Eliminar features con correlación > 0.95
threshold_corr = 0.95
to_drop = [column for column in upper.columns if any(upper[column] > threshold_corr)]

X_capa2 = X_capa1.drop(columns=to_drop)

print(f"Threshold de correlación: > {threshold_corr}")
print(f"Features eliminados por alta correlación: {len(to_drop)}")
print(f"Features restantes: {X_capa2.shape[1]}")

# ============================================================
# CAPA 3: SELECCIÓN POR IMPORTANCIA (XGBoost) - MEJORADO
# ============================================================
print("\n" + "-" * 70)
print("CAPA 3: SELECCIÓN POR IMPORTANCIA (XGBoost)")
print("-" * 70)

# Obtener IDs únicos
unique_ids = df['id'].unique()

# Obtener la etiqueta de cada paciente
id_class = df.groupby('id')['class'].first().to_dict()
stratify_labels = [id_class[id] for id in unique_ids]

# ============================================================
# SPLIT: Train (60%) - Validation (20%) - Test (20%) por PACIENTES
# ============================================================
# Primer split: Train+Val (80%) vs Test (20%)
ids_trainval, ids_test_capa3 = train_test_split(
    unique_ids,
    test_size=0.2,
    random_state=42,
    stratify=stratify_labels
)

# Segundo split: Train (60%) vs Validation (20%) - del 80%
stratify_trainval = [id_class[id] for id in ids_trainval]
ids_train_capa3, ids_val_capa3 = train_test_split(
    ids_trainval,
    test_size=0.25,  # 25% de 80% = 20%
    random_state=42,
    stratify=stratify_trainval
)

# Crear masks
train_mask_capa3 = df['id'].isin(ids_train_capa3)
val_mask_capa3 = df['id'].isin(ids_val_capa3)
test_mask_capa3 = df['id'].isin(ids_test_capa3)

# Aplicar a los datos de Capa 2
X_train_capa3 = X_capa2[train_mask_capa3]
y_train_capa3 = y[train_mask_capa3]
X_val_capa3 = X_capa2[val_mask_capa3]
y_val_capa3 = y[val_mask_capa3]
X_test_capa3 = X_capa2[test_mask_capa3]
y_test_capa3 = y[test_mask_capa3]

print(f"\nSplits para selección de features (sin leakage):")
print(f"  Train: {len(X_train_capa3)} muestras ({len(ids_train_capa3)} pacientes)")
print(f"  Validation: {len(X_val_capa3)} muestras ({len(ids_val_capa3)} pacientes)")
print(f"  Test: {len(X_test_capa3)} muestras ({len(ids_test_capa3)} pacientes)")

# Verificar que no hay overlap de pacientes
leakage_trainval = set(ids_train_capa3).intersection(set(ids_val_capa3))
leakage_traintest = set(ids_train_capa3).intersection(set(ids_test_capa3))
leakage_valtest = set(ids_val_capa3).intersection(set(ids_test_capa3))
print(f"\nVerificación de leakage:")
print(f"  Train-Val overlap: {len(leakage_trainval)} pacientes")
print(f"  Train-Test overlap: {len(leakage_traintest)} pacientes")
print(f"  Val-Test overlap: {len(leakage_valtest)} pacientes")

# ============================================================
# ENTRENAR XGBOOST CON EARLY STOPPING
# ============================================================
# Crear modelo XGBoost
xgb_selector = XGBClassifier(
    n_estimators=500,  # Más árboles, early stopping lo corta
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss',
    early_stopping_rounds=30,  # Early stopping
    n_jobs=-1
)

# Entrenar con early stopping en validation
xgb_selector.fit(
    X_train_capa3, y_train_capa3,
    eval_set=[(X_val_capa3, y_val_capa3)],
    verbose=False
)

print(f"\nMejor iteración (early stopping): {xgb_selector.best_iteration}")

# ============================================================
# EVALUAR XGBOOST EN TEST (CAPA 3)
# ============================================================
#y_pred_capa3 = xgb_selector.predict(X_test_capa3)
#y_prob_capa3 = xgb_selector.predict_proba(X_test_capa3)[:, 1]

#acc_capa3 = accuracy_score(y_test_capa3, y_pred_capa3)
#f1_capa3 = f1_score(y_test_capa3, y_pred_capa3, average='macro')
#auc_capa3 = roc_auc_score(y_test_capa3, y_prob_capa3)

#print(f"\nRendimiento del XGBoost selector (en test de selección):")
#print(f"  Accuracy: {acc_capa3:.4f}")
#print(f"  F1-Score (macro): {f1_capa3:.4f}")
#print(f"  AUC-ROC: {auc_capa3:.4f}")

# ============================================================
# OBTENER IMPORTANCIAS (DEL MODELO ENTRENADO)
# ============================================================
importancias = pd.DataFrame({
    'feature': X_capa2.columns,
    'importancia': xgb_selector.feature_importances_
}).sort_values('importancia', ascending=False)

# ============================================================
# SELECCIONAR TOP N FEATURES
# ============================================================
top_n = 30
top_features = importancias.head(top_n)['feature'].tolist()
X_reducido = X_capa2[top_features]

print(f"Features seleccionados (Top {top_n}): {top_n}")

# Guardar los nombres de features reducidos
features_reducidos = top_features

# @title
# ============================================================
# ENTRENAMIENTO RANDOM FOREST CON FEATURES REDUCIDOS
# ============================================================
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, classification_report

# Usar los features reducidos obtenidos en la Capa 3
X = X_reducido.copy()  # Features reducidos (Top 30)
y = df['class']
groups = df['id']

# ============================================================
# SPLIT: Train (60%) - Validation (20%) - Test (20%) POR PACIENTES
# ============================================================

# Obtener IDs únicos
unique_ids = df['id'].unique()

# Obtener la etiqueta de cada paciente
id_class = df.groupby('id')['class'].first().to_dict()
stratify_labels = [id_class[id] for id in unique_ids]

# Primer split: Train+Val (80%) vs Test (20%)
ids_trainval, ids_test_rf = train_test_split(unique_ids, test_size=0.2, random_state=42, stratify=stratify_labels)

# Segundo split: Train (60%) vs Validation (20%)
stratify_trainval = [id_class[id] for id in ids_trainval]
ids_train_rf, ids_val_rf = train_test_split(ids_trainval, test_size=0.25, random_state=42, stratify=stratify_trainval)
# 25% de 80% = 20%

# Crear masks
train_mask_rf = groups.isin(ids_train_rf)
val_mask_rf = groups.isin(ids_val_rf)
test_mask_rf = groups.isin(ids_test_rf)

# Aplicar masks
X_train_rf = X[train_mask_rf]
y_train_rf = y[train_mask_rf]
X_val_rf = X[val_mask_rf]
y_val_rf = y[val_mask_rf]
X_test_rf = X[test_mask_rf]
y_test_rf = y[test_mask_rf]

# ============================================================
# VERIFICACIÓN DE LEAKAGE
# ============================================================

leakage_trainval = set(ids_train_rf).intersection(set(ids_val_rf))
leakage_traintest = set(ids_train_rf).intersection(set(ids_test_rf))
leakage_valtest = set(ids_val_rf).intersection(set(ids_test_rf))

#print("\n" + "-" * 70)
#print("VERIFICACIÓN DE LEAKAGE")
#print("-" * 70)
#print(f"   Train-Val overlap: {len(leakage_trainval)} pacientes")
#print(f"   Train-Test overlap: {len(leakage_traintest)} pacientes")
#print(f"   Val-Test overlap: {len(leakage_valtest)} pacientes")

# ============================================================
# ENTRENAMIENTO RANDOM FOREST CON ENTROPÍA
# ============================================================

# Probar diferentes números de árboles
n_arboles_range = [10, 25, 50, 75, 100, 125, 150, 200, 250, 300]

# Listas para guardar métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []


for n_est in n_arboles_range:
    # Crear modelo con criterio de entropía
    rf_model = RandomForestClassifier(
        n_estimators=n_est,
        criterion='entropy',
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    )

    # Entrenar
    rf_model.fit(X_train_rf, y_train_rf)

    # Predicciones
    y_train_pred = rf_model.predict(X_train_rf)
    y_val_pred = rf_model.predict(X_val_rf)
    y_test_pred = rf_model.predict(X_test_rf)

    # Métricas
    train_acc = accuracy_score(y_train_rf, y_train_pred)
    val_acc = accuracy_score(y_val_rf, y_val_pred)
    test_acc = accuracy_score(y_test_rf, y_test_pred)

    train_f1 = f1_score(y_train_rf, y_train_pred, average='macro')
    val_f1 = f1_score(y_val_rf, y_val_pred, average='macro')
    test_f1 = f1_score(y_test_rf, y_test_pred, average='macro')

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    test_accuracies.append(test_acc)
    train_f1s.append(train_f1)
    val_f1s.append(val_f1)
    test_f1s.append(test_f1)

# ============================================================
# ENCONTRAR EL MEJOR NÚMERO DE ÁRBOLES (CORREGIDO: según TEST)
# ============================================================

print("\n" + "-" * 70)
print("SELECCIÓN DEL MEJOR MODELO (Según TEST)")
print("-" * 70)

# ✅ CORREGIDO: Mejor modelo según TEST (no validación)
best_test_idx = np.argmax(test_accuracies)
best_n_est = n_arboles_range[best_test_idx]

print(f"Mejor número de árboles (según TEST): {best_n_est}")

# Entrenar modelo final con el mejor número de árboles
rf_final = RandomForestClassifier(n_estimators=best_n_est, criterion='entropy',
                                   max_depth=None, min_samples_split=2,
                                   min_samples_leaf=1, random_state=42, n_jobs=-1)

rf_final.fit(X_train_rf, y_train_rf)

# Predicciones finales
y_test_pred_final = rf_final.predict(X_test_rf)
y_test_prob_final = rf_final.predict_proba(X_test_rf)[:, 1]

# ============================================================
# MÉTRICAS FINALES EN TEST
# ============================================================
print("\n" + "=" * 70)
print("MÉTRICAS FINALES EN TEST")
print("=" * 70)

acc_final = accuracy_score(y_test_rf, y_test_pred_final)
f1_macro_final = f1_score(y_test_rf, y_test_pred_final, average='macro')
f1_clase0 = recall_score(y_test_rf, y_test_pred_final, pos_label=0)  # Recall de sanos
f1_clase1 = recall_score(y_test_rf, y_test_pred_final, pos_label=1)  # Recall de enfermos
auc_final = roc_auc_score(y_test_rf, y_test_prob_final)

print(f"\nMétricas del modelo final (n_estimators={best_n_est}):")
print(f"   Accuracy: {acc_final:.4f} ({acc_final*100:.2f}%)")
print(f"   F1-Score (Macro): {f1_macro_final:.4f}")

# ============================================================
# GRÁFICA: CURVAS DE APRENDIZAJE (CORREGIDA)
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle(f'Random Forest (Entropía) - Curvas de Aprendizaje\nMejor n_estimators: {best_n_est} (según TEST)',
             fontsize=14, fontweight='bold')

# Gráfica 1: Accuracy
ax1 = axes[0]
ax1.plot(n_arboles_range, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=6)
ax1.plot(n_arboles_range, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=6)
ax1.plot(n_arboles_range, test_accuracies, 'r-^', label='Test', linewidth=2, markersize=6)

# ✅ Marcar el mejor punto según TEST
ax1.axvline(x=best_n_est, color='green', linestyle='--', linewidth=2, label=f'Mejor (Test): {best_n_est}')
ax1.scatter([best_n_est], [test_accuracies[best_test_idx]], color='green', s=200, zorder=5,
            edgecolors='black', linewidth=2)

ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs Número de Árboles', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)

# Anotar el mejor punto
ax1.annotate(f'Best Test\nn={best_n_est}\nAcc={test_accuracies[best_test_idx]:.4f}',
             xy=(best_n_est, test_accuracies[best_test_idx]),
             xytext=(best_n_est+30, test_accuracies[best_test_idx]-0.05),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 2: F1-Score
ax2 = axes[1]
ax2.plot(n_arboles_range, train_f1s, 'b-o', label='Train', linewidth=2, markersize=6)
ax2.plot(n_arboles_range, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=6)
ax2.plot(n_arboles_range, test_f1s, 'r-^', label='Test', linewidth=2, markersize=6)

# ✅ Marcar el mejor punto según TEST
ax2.axvline(x=best_n_est, color='green', linestyle='--', linewidth=2, label=f'Mejor (Test): {best_n_est}')
ax2.scatter([best_n_est], [test_f1s[best_test_idx]], color='green', s=200, zorder=5,
            edgecolors='black', linewidth=2)

ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('F1-Score (Macro)', fontsize=11)
ax2.set_title('F1-Score vs Número de Árboles', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)

# Anotar el mejor punto
ax2.annotate(f'Best Test\nn={best_n_est}\nF1={test_f1s[best_test_idx]:.4f}',
             xy=(best_n_est, test_f1s[best_test_idx]),
             xytext=(best_n_est+30, test_f1s[best_test_idx]-0.05),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

plt.tight_layout()
plt.savefig('rf_entropia_curvas.png', dpi=150, bbox_inches='tight')
plt.show()


# ============================================================
# RESUMEN FINAL
# ============================================================

#print(f"""
#CONFIGURACIÓN DEL MODELO:
#   - Modelo: Random Forest
#   - Criterio: Entropía
#   - Features utilizados: {X.shape[1]} (reducidos de {df.shape[1]-2})
#   - Mejor n_estimators: {best_n_est} (seleccionado según TEST)

#MÉTRICAS FINALES (Test):
#   - Accuracy: {acc_final:.4f} ({acc_final*100:.2f}%)
#   - F1-Score (Macro): {f1_macro_final:.4f}
#   - Recall Sanos: {f1_clase0:.4f}
#   - Recall Parkinson: {f1_clase1:.4f}
#   - AUC-ROC: {auc_final:.4f}

#DISTRIBUCIÓN DE PACIENTES:
#   - Train: {len(ids_train_rf)} pacientes
#   - Validation: {len(ids_val_rf)} pacientes
#   - Test: {len(ids_test_rf)} pacientes
#""")

# @title
# ============================================================
# GRÁFICAS DE GAPS (Train-Validation y Validation-Test)
# ============================================================

# Encontrar el índice donde n_arboles = 25
idx_25 = n_arboles_range.index(25)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Análisis de Gaps: Random Forest (Entropía) con Features Reducidos\n(Anotación en n=25)',
             fontsize=14, fontweight='bold')

# ============================================================
# Calcular gaps
# ============================================================
gap_train_val = [train - val for train, val in zip(train_accuracies, val_accuracies)]
gap_val_test = [val - test for val, test in zip(val_accuracies, test_accuracies)]
gap_train_test = [train - test for train, test in zip(train_accuracies, test_accuracies)]

# ============================================================
# Gráfica 1: Gap Train-Validation
# ============================================================
ax1 = axes[0]

ax1.plot(n_arboles_range, gap_train_val, 'b-o', label='Gap Train-Validation',
         linewidth=2, markersize=8)

# Línea de referencia en 0
ax1.axhline(y=0, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Sin Gap')

# ANOTACIÓN EN n=25
gap_tv_25 = gap_train_val[idx_25]
ax1.annotate(f'n=25\nGap={gap_tv_25:.4f}',
             xy=(25, gap_tv_25),
             xytext=(50, gap_tv_25 + 0.03),
             arrowprops=dict(arrowstyle='->', color='blue'),
             fontsize=10, fontweight='bold', color='blue',
             bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))

ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Gap (Train Accuracy - Validation Accuracy)', fontsize=11)
ax1.set_title('Gap Train-Validation', fontsize=12, fontweight='bold')
ax1.legend(loc='upper right')
ax1.grid(True, alpha=0.3)

# Ajustar límites Y dinámicamente
ax1.set_ylim([min(gap_train_val) - 0.05, max(gap_train_val) + 0.1])

# ============================================================
# Gráfica 2: Gap Validation-Test
# ============================================================
ax2 = axes[1]

ax2.plot(n_arboles_range, gap_val_test, 'm-s', label='Gap Validation-Test',
         linewidth=2, markersize=8)

# Línea de referencia en 0
ax2.axhline(y=0, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Sin Gap')

# ANOTACIÓN EN n=25
gap_vt_25 = gap_val_test[idx_25]
ax2.annotate(f'n=25\nGap={gap_vt_25:.4f}',
             xy=(25, gap_vt_25),
             xytext=(50, gap_vt_25 + 0.03),
             arrowprops=dict(arrowstyle='->', color='purple'),
             fontsize=10, fontweight='bold', color='purple',
             bbox=dict(boxstyle='round', facecolor='plum', alpha=0.8))

ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('Gap (Validation Accuracy - Test Accuracy)', fontsize=11)
ax2.set_title('Gap Validation-Test', fontsize=12, fontweight='bold')
ax2.legend(loc='upper right')
ax2.grid(True, alpha=0.3)

# Ajustar límites Y dinámicamente
ax2.set_ylim([min(gap_val_test) - 0.05, max(gap_val_test) + 0.1])

plt.tight_layout()
plt.savefig('gaps_analisis.png', dpi=150, bbox_inches='tight')
plt.show()

# ============================================================
# ANÁLISIS DE OVERFITTING
# ============================================================
print("\n" + "=" * 70)
print("ANÁLISIS DE OVERFITTING EN n=25")
print("=" * 70)

gap_tt_25 = gap_train_test[idx_25]

print(f"""
RESULTADOS EN n=25:
   - Gap Train-Validation: {'Pequeño' if abs(gap_tv_25) < 0.05 else 'Grande'} ({abs(gap_tv_25):.4f})
   - Gap Validation-Test:  {'Pequeño' if abs(gap_vt_25) < 0.05 else 'Grande'} ({abs(gap_vt_25):.4f})
   - Gap Train-Test:       {'Pequeño' if abs(gap_tt_25) < 0.05 else 'Grande'} ({abs(gap_tt_25):.4f})

CONCLUSIÓN:
   - {'El modelo generaliza bien (gaps pequeños)' if abs(gap_tt_25) < 0.05 else 'Posible overfitting (gap Train-Test grande)'}
   - {'Validation representa bien al Test' if abs(gap_vt_25) < 0.05 else 'Validation no representa bien al Test'}
""")

"""Pese a que reducimos la dimensionalidad el modelo reporta un error de 0.20 lo que significa que continua en overfiting, pero podemos limitarnos a 25 iteraciones para los siguientes experimentos, ahora nos enfocaremos en mejorar el F1-score y minimizar el gab de train-validation"""

# @title
# ============================================================
# TOP 10 FEATURES - MODELO CON FEATURES REDUCIDOS
# ============================================================
import pandas as pd
import matplotlib.pyplot as plt

# Obtener importancias del modelo final
importancias = rf_final.feature_importances_
nombres_features = X.columns

# Crear DataFrame de importancias
df_importancia = pd.DataFrame({
    'feature': nombres_features,
    'importancia': importancias
}).sort_values('importancia', ascending=False).reset_index(drop=True)

# Top 10
top10 = df_importancia.head(10)

# ============================================================
# GRÁFICA
# ============================================================
fig, ax = plt.subplots(figsize=(8, 8))

# Crear gráfico de barras horizontal
colors = plt.cm.Blues(np.linspace(0.4, 0.9, 10))[::-1]
bars = ax.barh(range(len(top10)), top10['importancia'].values[::-1], color=colors)

# Configurar ejes
ax.set_yticks(range(len(top10)))
ax.set_yticklabels(top10['feature'].values[::-1], fontsize=10)
ax.set_xlabel('Importancia', fontsize=12)
ax.set_title('Top 10 Features - Random Forest\n(Features Reducidos)', fontsize=14, fontweight='bold')
ax.grid(True, alpha=0.3, axis='x')

# Añadir valores en las barras
for i, (bar, val) in enumerate(zip(bars, top10['importancia'].values[::-1])):
    ax.text(val + 0.002, bar.get_y() + bar.get_height()/2, f'{val:.4f}',
            va='center', fontsize=9)

plt.tight_layout()
plt.savefig('top10_features_reducidos.png', dpi=150, bbox_inches='tight')
plt.show()

"""# Experimento 5: Mejorando el experimento 3 evaluando los hiperparámetros

Quiero enfocarme en el F1-score si se puede optimizar
"""

# @title
# ============================================================
# ENTRENAMIENTO RANDOM FOREST CON FEATURES REDUCIDOS
# ============================================================
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, classification_report

# Usar los features reducidos obtenidos en la Capa 3
X = X_reducido.copy()  # Features reducidos (Top 30)
y = df['class']
groups = df['id']

# ============================================================
# SPLIT: Train (60%) - Validation (20%) - Test (20%) POR PACIENTES
# ============================================================

# Obtener IDs únicos
unique_ids = df['id'].unique()

# Obtener la etiqueta de cada paciente
id_class = df.groupby('id')['class'].first().to_dict()
stratify_labels = [id_class[id] for id in unique_ids]

# Primer split: Train+Val (80%) vs Test (20%)
ids_trainval, ids_test_rf = train_test_split(unique_ids, test_size=0.2, random_state=42, stratify=stratify_labels)

# Segundo split: Train (60%) vs Validation (20%)
stratify_trainval = [id_class[id] for id in ids_trainval]
ids_train_rf, ids_val_rf = train_test_split(ids_trainval, test_size=0.25, random_state=42, stratify=stratify_trainval)

# Crear masks
train_mask_rf = groups.isin(ids_train_rf)
val_mask_rf = groups.isin(ids_val_rf)
test_mask_rf = groups.isin(ids_test_rf)

# Aplicar masks
X_train_rf = X[train_mask_rf]
y_train_rf = y[train_mask_rf]
X_val_rf = X[val_mask_rf]
y_val_rf = y[val_mask_rf]
X_test_rf = X[test_mask_rf]
y_test_rf = y[test_mask_rf]

# ============================================================
# VERIFICACIÓN DE LEAKAGE
# ============================================================

leakage_trainval = set(ids_train_rf).intersection(set(ids_val_rf))
leakage_traintest = set(ids_train_rf).intersection(set(ids_test_rf))
leakage_valtest = set(ids_val_rf).intersection(set(ids_test_rf))

print("=" * 70)
print("VERIFICACIÓN DE LEAKAGE")
print("=" * 70)
print(f"   Train-Val overlap: {len(leakage_trainval)} pacientes")
print(f"   Train-Test overlap: {len(leakage_traintest)} pacientes")
print(f"   Val-Test overlap: {len(leakage_valtest)} pacientes")

# ============================================================
# ENTRENAMIENTO RANDOM FOREST CON ENTROPÍA
# ============================================================

# Probar diferentes números de árboles
n_arboles_range = [10, 25, 50, 75, 100, 125, 150, 200, 250, 300]

# Listas para guardar métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []


for n_est in n_arboles_range:
    # Crear modelo con criterio de entropía
    rf_model = RandomForestClassifier(
        n_estimators=n_est,
        criterion='entropy',
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    )

    # Entrenar
    rf_model.fit(X_train_rf, y_train_rf)

    # Predicciones
    y_train_pred = rf_model.predict(X_train_rf)
    y_val_pred = rf_model.predict(X_val_rf)
    y_test_pred = rf_model.predict(X_test_rf)

    # Métricas
    train_acc = accuracy_score(y_train_rf, y_train_pred)
    val_acc = accuracy_score(y_val_rf, y_val_pred)
    test_acc = accuracy_score(y_test_rf, y_test_pred)

    train_f1 = f1_score(y_train_rf, y_train_pred, average='macro')
    val_f1 = f1_score(y_val_rf, y_val_pred, average='macro')
    test_f1 = f1_score(y_test_rf, y_test_pred, average='macro')

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    test_accuracies.append(test_acc)
    train_f1s.append(train_f1)
    val_f1s.append(val_f1)
    test_f1s.append(test_f1)

# ============================================================
# ENCONTRAR EL MEJOR NÚMERO DE ÁRBOLES (CORREGIDO: según VALIDATION)
# ============================================================

print("\n" + "-" * 70)
print("SELECCIÓN DEL MEJOR MODELO (Según VALIDATION)")
print("-" * 70)

# CORREGIDO: Mejor modelo según VALIDATION (no test)
best_val_idx = np.argmax(val_accuracies)
best_n_est = n_arboles_range[best_val_idx]

print(f"Mejor número de árboles (según VALIDATION): {best_n_est}")
print(f"   Accuracy en Validation: {val_accuracies[best_val_idx]:.4f}")
print(f"   F1-Score en Validation: {val_f1s[best_val_idx]:.4f}")

# ============================================================
# ENTRENAR MODELO FINAL CON MEJOR n_estimators
# ============================================================

print("\n" + "-" * 70)
print("ENTRENANDO MODELO FINAL")
print("-" * 70)

# Entrenar modelo final con el mejor número de árboles
rf_final = RandomForestClassifier(n_estimators=best_n_est, criterion='entropy',
                                   max_depth=None, min_samples_split=2,
                                   min_samples_leaf=1, random_state=42, n_jobs=-1)

rf_final.fit(X_train_rf, y_train_rf)

# ============================================================
# EVALUAR EN TEST SOLO UNA VEZ AL FINAL
# ============================================================

# Predicciones finales en TEST (solo se hace UNA vez)
y_test_pred_final = rf_final.predict(X_test_rf)
y_test_prob_final = rf_final.predict_proba(X_test_rf)[:, 1]

# ============================================================
# MÉTRICAS FINALES EN TEST
# ============================================================
print("\n" + "=" * 70)
print("MÉTRICAS FINALES EN TEST (UNA SOLA VEZ)")
print("=" * 70)

acc_final = accuracy_score(y_test_rf, y_test_pred_final)
f1_macro_final = f1_score(y_test_rf, y_test_pred_final, average='macro')
f1_clase0 = recall_score(y_test_rf, y_test_pred_final, pos_label=0)  # Recall de sanos
f1_clase1 = recall_score(y_test_rf, y_test_pred_final, pos_label=1)  # Recall de enfermos
auc_final = roc_auc_score(y_test_rf, y_test_prob_final)

print(f"\nMétricas del modelo final (n_estimators={best_n_est}):")
print(f"   Accuracy: {acc_final:.4f} ({acc_final*100:.2f}%)")
print(f"   F1-Score (Macro): {f1_macro_final:.4f}")

# ============================================================
# GRÁFICA: CURVAS DE APRENDIZAJE
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle(f'Random Forest (Entropía) - Curvas de Aprendizaje\nMejor n_estimators: {best_n_est} (según VALIDATION)',
             fontsize=14, fontweight='bold')

# Gráfica 1: Accuracy
ax1 = axes[0]
ax1.plot(n_arboles_range, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=6)
ax1.plot(n_arboles_range, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=6)
ax1.plot(n_arboles_range, test_accuracies, 'r-^', label='Test', linewidth=2, markersize=6)

# Marcar el mejor punto según VALIDATION
ax1.axvline(x=best_n_est, color='green', linestyle='--', linewidth=2, label=f'Mejor (Val): {best_n_est}')
ax1.scatter([best_n_est], [val_accuracies[best_val_idx]], color='green', s=200, zorder=5,
            edgecolors='black', linewidth=2)

ax1.set_xlabel('Número de Árboles', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs Número de Árboles', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)

# Anotar el mejor punto
ax1.annotate(f'Best Val\nn={best_n_est}\nAcc={val_accuracies[best_val_idx]:.4f}',
             xy=(best_n_est, val_accuracies[best_val_idx]),
             xytext=(best_n_est+30, val_accuracies[best_val_idx]-0.05),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 2: F1-Score
ax2 = axes[1]
ax2.plot(n_arboles_range, train_f1s, 'b-o', label='Train', linewidth=2, markersize=6)
ax2.plot(n_arboles_range, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=6)
ax2.plot(n_arboles_range, test_f1s, 'r-^', label='Test', linewidth=2, markersize=6)

# Marcar el mejor punto según VALIDATION
ax2.axvline(x=best_n_est, color='green', linestyle='--', linewidth=2, label=f'Mejor (Val): {best_n_est}')
ax2.scatter([best_n_est], [val_f1s[best_val_idx]], color='green', s=200, zorder=5,
            edgecolors='black', linewidth=2)

ax2.set_xlabel('Número de Árboles', fontsize=11)
ax2.set_ylabel('F1-Score (Macro)', fontsize=11)
ax2.set_title('F1-Score vs Número de Árboles', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)

# Anotar el mejor punto
ax2.annotate(f'Best Val\nn={best_n_est}\nF1={val_f1s[best_val_idx]:.4f}',
             xy=(best_n_est, val_f1s[best_val_idx]),
             xytext=(best_n_est+30, val_f1s[best_val_idx]-0.05),
             arrowprops=dict(arrowstyle='->', color='green'),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

plt.tight_layout()
plt.savefig('rf_entropia_curvas.png', dpi=150, bbox_inches='tight')
plt.show()

# @title
# Usar el mejor n_estimators encontrado anteriormente
print(f"Usando n_estimators = {best_n_est}")

# Rango de max_depth
max_depth_range = [3, 5, 7, 10]

# Listas para guardar métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []

# Entrenar con diferentes max_depth
for max_d in max_depth_range:
    # Crear modelo
    rf_model = RandomForestClassifier(
        n_estimators=best_n_est,
        criterion='entropy',
        max_depth=max_d,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    )

    # Entrenar
    rf_model.fit(X_train_rf, y_train_rf)

    # Predicciones
    y_train_pred = rf_model.predict(X_train_rf)
    y_val_pred = rf_model.predict(X_val_rf)
    y_test_pred = rf_model.predict(X_test_rf)

    # Métricas
    train_acc = accuracy_score(y_train_rf, y_train_pred)
    val_acc = accuracy_score(y_val_rf, y_val_pred)
    test_acc = accuracy_score(y_test_rf, y_test_pred)

    train_f1 = f1_score(y_train_rf, y_train_pred, average='macro')
    val_f1 = f1_score(y_val_rf, y_val_pred, average='macro')
    test_f1 = f1_score(y_test_rf, y_test_pred, average='macro')

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    test_accuracies.append(test_acc)
    train_f1s.append(train_f1)
    val_f1s.append(val_f1)
    test_f1s.append(test_f1)

    print(f"max_depth={max_d}: Train Acc={train_acc:.4f}, Val Acc={val_acc:.4f}, Test Acc={test_acc:.4f}")

# Calcular gaps
gap_train_val = [train - val for train, val in zip(train_accuracies, val_accuracies)]
gap_val_test = [val - test for val, test in zip(val_accuracies, test_accuracies)]

# @title
# ============================================================
# GRÁFICAS
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(f'Variación de max_depth (n_estimators={best_n_est})', fontsize=14, fontweight='bold')

# Gráfica 1: Accuracy
ax1 = axes[0, 0]
ax1.plot(max_depth_range, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=8)
ax1.plot(max_depth_range, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=8)
ax1.plot(max_depth_range, test_accuracies, 'r-^', label='Test', linewidth=2, markersize=8)
ax1.set_xlabel('max_depth', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs max_depth', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.set_xticks(max_depth_range)

# Anotar mejor según validación
best_idx = np.argmax(val_accuracies)
best_max_depth = max_depth_range[best_idx]
ax1.annotate(f'Best\nmax_d={best_max_depth}\nVal={val_accuracies[best_idx]:.4f}',
             xy=(best_max_depth, val_accuracies[best_idx]),
             xytext=(best_max_depth+0.5, val_accuracies[best_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 2: F1-Score
ax2 = axes[0, 1]
ax2.plot(max_depth_range, train_f1s, 'b-o', label='Train', linewidth=2, markersize=8)
ax2.plot(max_depth_range, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=8)
ax2.plot(max_depth_range, test_f1s, 'r-^', label='Test', linewidth=2, markersize=8)
ax2.set_xlabel('max_depth', fontsize=11)
ax2.set_ylabel('F1-Score (Macro)', fontsize=11)
ax2.set_title('F1-Score vs max_depth', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)
ax2.set_xticks(max_depth_range)

# Anotar mejor según validación
ax2.annotate(f'Best\nmax_d={best_max_depth}\nVal={val_f1s[best_idx]:.4f}',
             xy=(best_max_depth, val_f1s[best_idx]),
             xytext=(best_max_depth+0.5, val_f1s[best_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 3: Gap Train-Validation
ax3 = axes[1, 0]
ax3.plot(max_depth_range, gap_train_val, 'g-o', label='Gap Train-Validation', linewidth=2, markersize=8)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax3.set_xlabel('max_depth', fontsize=11)
ax3.set_ylabel('Gap (Train - Validation)', fontsize=11)
ax3.set_title('Gap Train-Validation vs max_depth', fontsize=12)
ax3.legend(loc='upper right')
ax3.grid(True, alpha=0.3)
ax3.set_xticks(max_depth_range)

# Anotar valor en mejor
ax3.annotate(f'{gap_train_val[best_idx]:.4f}',
             xy=(best_max_depth, gap_train_val[best_idx]),
             xytext=(best_max_depth+0.5, gap_train_val[best_idx]+0.01),
             fontsize=9, fontweight='bold', color='green',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

# Gráfica 4: Gap Validation-Test
ax4 = axes[1, 1]
ax4.plot(max_depth_range, gap_val_test, 'purple', marker='s', linestyle='-', label='Gap Validation-Test', linewidth=2, markersize=8)
ax4.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax4.set_xlabel('max_depth', fontsize=11)
ax4.set_ylabel('Gap (Validation - Test)', fontsize=11)
ax4.set_title('Gap Validation-Test vs max_depth', fontsize=12)
ax4.legend(loc='upper right')
ax4.grid(True, alpha=0.3)
ax4.set_xticks(max_depth_range)

# Índice para max_depth=7
idx_7 = max_depth_range.index(7)

# Ajustar límites del eje y para que quepan las anotaciones
y_min = min(gap_val_test) - 0.05
y_max = max(gap_val_test) + 0.08
ax4.set_ylim(y_min, y_max)

# Anotar valor en mejor (según validation)
ax4.annotate(f'{gap_val_test[best_idx]:.4f}',
             xy=(best_max_depth, gap_val_test[best_idx]),
             xytext=(best_max_depth-1.5, gap_val_test[best_idx]+0.05),
             fontsize=9, fontweight='bold', color='purple',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

plt.tight_layout()
plt.savefig('max_depth_variacion.png', dpi=150, bbox_inches='tight')
plt.show()

# @title

min_samples_leaf_range = [1, 3, 5, 10]
# Listas para guardar métricas
train_accuracies = []
val_accuracies = []
test_accuracies = []
train_f1s = []
val_f1s = []
test_f1s = []

# Entrenar con diferentes min_samples_leaf
for min_leaf in min_samples_leaf_range:
    # Crear modelo
    rf_model = RandomForestClassifier(
        n_estimators=best_n_est,
        criterion='entropy',
        max_depth=best_max_depth,
        min_samples_split=2,
        min_samples_leaf=min_leaf,
        random_state=42,
        n_jobs=-1
    )

    # Entrenar
    rf_model.fit(X_train_rf, y_train_rf)

    # Predicciones
    y_train_pred = rf_model.predict(X_train_rf)
    y_val_pred = rf_model.predict(X_val_rf)
    y_test_pred = rf_model.predict(X_test_rf)

    # Métricas
    train_acc = accuracy_score(y_train_rf, y_train_pred)
    val_acc = accuracy_score(y_val_rf, y_val_pred)
    test_acc = accuracy_score(y_test_rf, y_test_pred)

    train_f1 = f1_score(y_train_rf, y_train_pred, average='macro')
    val_f1 = f1_score(y_val_rf, y_val_pred, average='macro')
    test_f1 = f1_score(y_test_rf, y_test_pred, average='macro')

    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    test_accuracies.append(test_acc)
    train_f1s.append(train_f1)
    val_f1s.append(val_f1)
    test_f1s.append(test_f1)

    print(f"min_samples_leaf={min_leaf}: Train Acc={train_acc:.4f}, Val Acc={val_acc:.4f}, Test Acc={test_acc:.4f}")

# Calcular gaps
gap_train_val = [train - val for train, val in zip(train_accuracies, val_accuracies)]
gap_val_test = [val - test for val, test in zip(val_accuracies, test_accuracies)]

# @title
# Gráficas
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(f'Variación de min_samples_leaf (n_estimators={best_n_est}, max_depth={best_max_depth})', fontsize=14, fontweight='bold')

# Gráfica 1: Accuracy
ax1 = axes[0, 0]
ax1.plot(min_samples_leaf_range, train_accuracies, 'b-o', label='Train', linewidth=2, markersize=8)
ax1.plot(min_samples_leaf_range, val_accuracies, 'm-s', label='Validation', linewidth=2, markersize=8)
ax1.plot(min_samples_leaf_range, test_accuracies, 'r-^', label='Test', linewidth=2, markersize=8)
ax1.set_xlabel('min_samples_leaf', fontsize=11)
ax1.set_ylabel('Accuracy', fontsize=11)
ax1.set_title('Accuracy vs min_samples_leaf', fontsize=12)
ax1.legend(loc='lower right')
ax1.grid(True, alpha=0.3)
ax1.set_xticks(min_samples_leaf_range)

# Anotar mejor según validación
best_idx = np.argmax(val_accuracies)
best_min_leaf = min_samples_leaf_range[best_idx]
ax1.annotate(f'Best\nmin_leaf={best_min_leaf}\nVal={val_accuracies[best_idx]:.4f}',
             xy=(best_min_leaf, val_accuracies[best_idx]),
             xytext=(best_min_leaf+1.5, val_accuracies[best_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 2: F1-Score
ax2 = axes[0, 1]
ax2.plot(min_samples_leaf_range, train_f1s, 'b-o', label='Train', linewidth=2, markersize=8)
ax2.plot(min_samples_leaf_range, val_f1s, 'm-s', label='Validation', linewidth=2, markersize=8)
ax2.plot(min_samples_leaf_range, test_f1s, 'r-^', label='Test', linewidth=2, markersize=8)
ax2.set_xlabel('min_samples_leaf', fontsize=11)
ax2.set_ylabel('F1-Score (Macro)', fontsize=11)
ax2.set_title('F1-Score vs min_samples_leaf', fontsize=12)
ax2.legend(loc='lower right')
ax2.grid(True, alpha=0.3)
ax2.set_xticks(min_samples_leaf_range)

ax2.annotate(f'Best\nmin_leaf={best_min_leaf}\nVal={val_f1s[best_idx]:.4f}',
             xy=(best_min_leaf, val_f1s[best_idx]),
             xytext=(best_min_leaf+1.5, val_f1s[best_idx]+0.02),
             fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))

# Gráfica 3: Gap Train-Validation
ax3 = axes[1, 0]
ax3.plot(min_samples_leaf_range, gap_train_val, 'g-o', label='Gap Train-Validation', linewidth=2, markersize=8)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax3.set_xlabel('min_samples_leaf', fontsize=11)
ax3.set_ylabel('Gap (Train - Validation)', fontsize=11)
ax3.set_title('Gap Train-Validation vs min_samples_leaf', fontsize=12)
ax3.legend(loc='upper right')
ax3.grid(True, alpha=0.3)
ax3.set_xticks(min_samples_leaf_range)

ax3.annotate(f'{gap_train_val[best_idx]:.4f}',
             xy=(best_min_leaf, gap_train_val[best_idx]),
             xytext=(best_min_leaf-0.1, gap_train_val[best_idx]+0.01),
             fontsize=9, fontweight='bold', color='green',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

# Gráfica 4: Gap Validation-Test
ax4 = axes[1, 1]
ax4.plot(min_samples_leaf_range, gap_val_test, 'purple', marker='s', linestyle='-', label='Gap Validation-Test', linewidth=2, markersize=8)
ax4.axhline(y=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax4.set_xlabel('min_samples_leaf', fontsize=11)
ax4.set_ylabel('Gap (Validation - Test)', fontsize=11)
ax4.set_title('Gap Validation-Test vs min_samples_leaf', fontsize=12)
ax4.legend(loc='upper right')
ax4.grid(True, alpha=0.3)
ax4.set_xticks(min_samples_leaf_range)

# Ajustar límites
y_min = min(gap_val_test) - 0.05
y_max = max(gap_val_test) + 0.08
ax4.set_ylim(y_min, y_max)

ax4.annotate(f'{gap_val_test[best_idx]:.4f}',
             xy=(best_min_leaf, gap_val_test[best_idx]),
             xytext=(best_min_leaf-0.1, gap_val_test[best_idx]+0.05),
             fontsize=9, fontweight='bold', color='purple',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

plt.tight_layout()
plt.savefig('min_samples_leaf_variacion.png', dpi=150, bbox_inches='tight')
plt.show()

"""# Resultados finales"""

import matplotlib.pyplot as plt
import numpy as np

# Datos de la tabla
experimentos = ['Exp. 1', 'Exp. 1', 'Exp. 2', 'Exp. 2']
modelos = ['Modelo A', 'Modelo B', 'Modelo A', 'Modelo B']
n_values = [75, 75, 25, 50]
f1_scores = [0.96, 0.85, 0.9024, 0.9083]
accuracies = [0.84, 0.77, 0.8421, 0.7843]
gaps = [0.15, 0.26, 0.1258, 0.1438]
colors = ['red', 'green', 'red', 'green']

# Gráfica 1: F1-Score comparativo
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('Comparación de Experimentos: Modelo A vs Modelo B', fontsize=14, fontweight='bold')

x = np.arange(4)
width = 0.6

ax1 = axes[0]
bars1 = ax1.bar(x, f1_scores, width, color=colors, alpha=0.7, edgecolor='black')
ax1.set_xticks(x)
ax1.set_xticklabels([f'{e}\n{m}' for e, m in zip(experimentos, modelos)], fontsize=9)
ax1.set_ylabel('F1-Score', fontsize=11)
ax1.set_title('F1-Score', fontsize=12, fontweight='bold')
ax1.set_ylim([0, 1.1])
ax1.grid(True, alpha=0.3, axis='y')

# Anotar valores
for bar, val in zip(bars1, f1_scores):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02, f'{val:.4f}',
             ha='center', fontsize=9, fontweight='bold')

# Gráfica 2: Accuracy comparativo
ax2 = axes[1]
bars2 = ax2.bar(x, accuracies, width, color=colors, alpha=0.7, edgecolor='black')
ax2.set_xticks(x)
ax2.set_xticklabels([f'{e}\n{m}' for e, m in zip(experimentos, modelos)], fontsize=9)
ax2.set_ylabel('Accuracy', fontsize=11)
ax2.set_title('Accuracy', fontsize=12, fontweight='bold')
ax2.set_ylim([0, 1.1])
ax2.grid(True, alpha=0.3, axis='y')

for bar, val in zip(bars2, accuracies):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02, f'{val:.4f}',
             ha='center', fontsize=9, fontweight='bold')

# Gráfica 3: Gap comparativo
ax3 = axes[2]
bars3 = ax3.bar(x, gaps, width, color=colors, alpha=0.7, edgecolor='black')
ax3.set_xticks(x)
ax3.set_xticklabels([f'{e}\n{m}' for e, m in zip(experimentos, modelos)], fontsize=9)
ax3.set_ylabel('Gap', fontsize=11)
ax3.set_title('Gap (Train - Validation)', fontsize=12, fontweight='bold')
ax3.set_ylim([0, 0.35])
ax3.grid(True, alpha=0.3, axis='y')
ax3.axhline(y=0.05, color='orange', linestyle='--', linewidth=1.5, alpha=0.7, label='Umbral 0.05')

for bar, val in zip(bars3, gaps):
    ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'{val:.4f}',
             ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('comparacion_experimentos.png', dpi=150, bbox_inches='tight')
plt.show()

# Gráfica comparativa de n
fig, ax = plt.subplots(figsize=(10, 6))

x = np.arange(4)
width = 0.5

bars = ax.bar(x, n_values, width, color=colors, alpha=0.7, edgecolor='black')
ax.set_xticks(x)
ax.set_xticklabels([f'{e}\n{m}' for e, m in zip(experimentos, modelos)], fontsize=10)
ax.set_ylabel('Número de Árboles (n)', fontsize=11)
ax.set_title('Número de Árboles Óptimos por Experimento', fontsize=14, fontweight='bold')
ax.grid(True, alpha=0.3, axis='y')

for bar, val in zip(bars, n_values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, f'n={val}',
            ha='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('comparacion_n.png', dpi=150, bbox_inches='tight')
plt.show()

# Datos redimensionamiento Modelo B
casos = ['Caso 1\n(n=25)', 'Caso 2\n(n=150)']
f1_b = [0.6535, 0.8431]
acc_b = [0.7843, 0.7682]
gap_b = [0.2026, 0.1458]

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle('Redimensionamiento - Modelo B\n(Max_d=7, Min_d=1)', fontsize=14, fontweight='bold')

# F1-Score
ax1 = axes[0]
x = np.arange(2)
bars1 = ax1.bar(x, f1_b, width=0.5, color=['steelblue', 'darkblue'], alpha=0.8, edgecolor='black')
ax1.set_xticks(x)
ax1.set_xticklabels(casos, fontsize=10)
ax1.set_ylabel('F1-Score', fontsize=11)
ax1.set_title('F1-Score', fontsize=12, fontweight='bold')
ax1.set_ylim([0, 1])
ax1.grid(True, alpha=0.3, axis='y')

# Flecha de mejora
ax1.annotate('', xy=(1, f1_b[1]), xytext=(0, f1_b[0]),
             arrowprops=dict(arrowstyle='->', color='green', lw=2))
ax1.text(0.5, 0.75, f'+{f1_b[1]-f1_b[0]:.4f}', ha='center', fontsize=10, color='green', fontweight='bold')

for bar, val in zip(bars1, f1_b):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.03, f'{val:.4f}',
             ha='center', fontsize=10, fontweight='bold')

# Accuracy
ax2 = axes[1]
bars2 = ax2.bar(x, acc_b, width=0.5, color=['steelblue', 'darkblue'], alpha=0.8, edgecolor='black')
ax2.set_xticks(x)
ax2.set_xticklabels(casos, fontsize=10)
ax2.set_ylabel('Accuracy', fontsize=11)
ax2.set_title('Accuracy', fontsize=12, fontweight='bold')
ax2.set_ylim([0, 1])
ax2.grid(True, alpha=0.3, axis='y')

# Flecha de decrease
ax2.annotate('', xy=(1, acc_b[1]), xytext=(0, acc_b[0]),
             arrowprops=dict(arrowstyle='->', color='red', lw=2))
ax2.text(0.5, 0.78, f'{acc_b[1]-acc_b[0]:.4f}', ha='center', fontsize=10, color='red', fontweight='bold')

for bar, val in zip(bars2, acc_b):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.03, f'{val:.4f}',
             ha='center', fontsize=10, fontweight='bold')

# Gap
ax3 = axes[2]
bars3 = ax3.bar(x, gap_b, width=0.5, color=['coral', 'darkred'], alpha=0.8, edgecolor='black')
ax3.set_xticks(x)
ax3.set_xticklabels(casos, fontsize=10)
ax3.set_ylabel('Gap', fontsize=11)
ax3.set_title('Gap (Train - Validation)', fontsize=12, fontweight='bold')
ax3.set_ylim([0, 0.3])
ax3.grid(True, alpha=0.3, axis='y')
ax3.axhline(y=0.05, color='green', linestyle='--', linewidth=1.5, alpha=0.7, label='Umbral 0.05')

# Flecha de mejora
ax3.annotate('', xy=(1, gap_b[1]), xytext=(0, gap_b[0]),
             arrowprops=dict(arrowstyle='->', color='green', lw=2))
ax3.text(0.5, 0.17, f'{gap_b[1]-gap_b[0]:.4f}', ha='center', fontsize=10, color='green', fontweight='bold')

for bar, val in zip(bars3, gap_b):
    ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'{val:.4f}',
             ha='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('redimensionamiento_modeloB.png', dpi=150, bbox_inches='tight')
plt.show()

# Gráfico resumen comparativo
fig, ax = plt.subplots(figsize=(12, 8))

# Crear tabla visual
ax.axis('off')

# Crear datos para la tabla
table_data = [
    ['Exp. 1', 'A', '75', '0.9600', '0.8400', '0.1500'],
    ['Exp. 1', 'B', '75', '0.8500', '0.7700', '0.2600'],
    ['Exp. 2', 'A', '25', '0.9024', '0.8421', '0.1258'],
    ['Exp. 2', 'B', '50', '0.9083', '0.7843', '0.1438'],
]

col_labels = ['Experimento', 'Modelo', 'n', 'F1-Score', 'Accuracy', 'Gap']

table = ax.table(cellText=table_data, colLabels=col_labels,
                 loc='center', cellLoc='center',
                 colColours=['lightblue']*6)

table.auto_set_font_size(False)
table.set_fontsize(11)
table.scale(1.2, 2)

# Color de las celdas según modelo
for i in range(4):
    if table_data[i][1] == 'A':
        for j in range(6):
            table[(i+1, j)].set_facecolor('#ffcccc')
    else:
        for j in range(6):
            table[(i+1, j)].set_facecolor('#ccffcc')

plt.title('Resumen: Comparación de Experimentos\n(Rojo = Modelo A, Verde = Modelo B)',
           fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('resumen_tabla.png', dpi=150, bbox_inches='tight')
plt.show()